Traceback (most recent call last):
  File "train.py", line 79, in <module>
    train_dreamer(exp, n_workers=args.n_workers)
  File "train.py", line 22, in train_dreamer
    runner.run(exp.steps, exp.episodes)
  File "/home/workdir/agent/runners/DreamerRunner.py", line 42, in run
    wandb.log({'reward': info["reward"], 'steps': cur_steps})
KeyError: 'reward'
Traceback (most recent call last):
  File "train.py", line 79, in <module>
    train_dreamer(exp, n_workers=args.n_workers)
  File "train.py", line 22, in train_dreamer
    runner.run(exp.steps, exp.episodes)
  File "/home/workdir/agent/runners/DreamerRunner.py", line 42, in run
    wandb.log({'reward': info["reward"], 'steps': cur_steps})
KeyError: 'reward'